#!/usr/bin/env bash
#from https://wiki.archlinux.org/index.php/Firefox_on_RAM

static=main
link=`ls $HOME/.mozilla/firefox | grep default`
volatile=/dev/shm/firefox-$USER

IFS=
set -efu

cd ~/.mozilla/firefox

if [ ! -r $volatile ]; then
   mkdir -m0700 $volatile
fi

if [ "$(readlink $link)" != "$volatile" ]; then
   mv $link $static
   ln -s $volatile $link
fi

if [ -e $link/.unpacked ]; then
   rsync -av --delete --exclude .unpacked ./$link/ ./$static/
else
   rsync -av ./$static/ ./$link/
   touch $link/.unpacked
fi

count=`cat /tmp/fsync`
if [ "$count" ]; then
   count=$((count + 1))
else
   count=0
fi

echo "$count" | tee /tmp/fsync
