#!/usr/bin/env bash

a=

if [ -d "/sys/class/net/tap0" ]; then
   a="/sys/class/net/tap0"
elif [ -d "/sys/class/net/tun0" ]; then
   a="/sys/class/net/tun0"
fi

if [ "$a" == "" ]; then
  if [ -f "$HOME/.config/locator.conf" ]; then
     cat "$HOME/.config/locator.conf" | while read line; do
        pid=`pidof "$line"`
        [[ "$pid" ]] && kill "$pid"
     done
  fi
  if [ -f "/tmp/locator.tmp" ]; then
      rm "/tmp/locator.tmp"
  fi
  echo "No VPN"
else
   place=
   if [ -f "/tmp/locator.tmp" ]; then
      dev="`cat /tmp/locator.tmp | grep "dev:" | cut --complement -d: -f 1`"
      if [ "$dev" == "`cat "$a/address"`" ]; then
         place="`cat /tmp/locator.tmp | grep "place:" | cut -d: -f 2`"
      else
         rm "/tmp/locator.tmp" 
      fi
   fi

   if [ "$place" == "" ]; then
      place="`w3m duckduckgo.com/html/?q=my+ip | grep -m 1 "Your IP address is"| cut --complement -d' ' -f 1-6`"
      echo -e "dev:`cat "$a/address"`\nplace:$place" > "/tmp/locator.tmp"
   fi

   echo "$place"
fi
