#!/usr/bin/env bash

source "$HOME/.config/user-dirs.dirs"

cur="$XDG_VIDEOS_DIR"
nex=""

while [ -d "$cur$nex" ]; do
   cur="$cur$nex"
   nex="/""`ls "$cur" | rofi -dmenu`"
   if [ "$nex" == "/" ]; then
      exit;
   fi
done

exo-open "$cur$nex"
